import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { createClient } from "@supabase/supabase-js";

const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY // ✅ server only
);

export async function GET(req, { params }) {
  const id = params.id;

  const { data, error } = await supabaseAdmin
    .from("teacher_applications")
    .select("*")
    .eq("id", id)
    .single();

  if (error || !data) {
    return new Response("Not found", { status: 404 });
  }

  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([595.28, 841.89]); // A4
  const { width, height } = page.getSize();

  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  // Colors
  const primary = rgb(0.12, 0.32, 0.80); // blue
  const text = rgb(0.12, 0.12, 0.12);
  const light = rgb(0.92, 0.95, 1);

  // Header
  page.drawRectangle({ x: 0, y: height - 90, width, height: 90, color: light });
  page.drawText("EXCELLENT COACHING", {
    x: 40,
    y: height - 55,
    size: 18,
    font: bold,
    color: primary,
  });
  page.drawText("Teacher Job Application", {
    x: 40,
    y: height - 75,
    size: 12,
    font,
    color: text,
  });

  // Right meta
  page.drawText(`Application ID: ${data.id}`, {
    x: width - 210,
    y: height - 55,
    size: 10,
    font,
    color: text,
  });
  page.drawText(`Date: ${new Date(data.created_at).toLocaleString()}`, {
    x: width - 210,
    y: height - 70,
    size: 10,
    font,
    color: text,
  });

  // Watermark
  page.drawText("EXCELLENT COACHING", {
    x: 85,
    y: 420,
    size: 46,
    font: bold,
    color: rgb(0.85, 0.88, 0.95),
    rotate: { type: "degrees", angle: 30 },
    opacity: 0.25,
  });

  // Body box
  page.drawRectangle({
    x: 35,
    y: 110,
    width: width - 70,
    height: height - 220,
    borderColor: rgb(0.8, 0.85, 0.95),
    borderWidth: 1,
    color: rgb(1, 1, 1),
  });

  const line = (label, value, y) => {
    page.drawText(label, { x: 55, y, size: 11, font: bold, color: text });
    page.drawText(value || "-", { x: 220, y, size: 11, font, color: text });
  };

  let y = height - 130;
  line("Full Name:", data.full_name, y); y -= 22;
  line("Phone:", data.phone, y); y -= 22;
  line("WhatsApp:", data.whatsapp, y); y -= 22;
  line("Email:", data.email, y); y -= 22;
  line("City:", data.city, y); y -= 22;
  line("Address:", (data.address || "-").slice(0, 60), y); y -= 22;

  y -= 8;
  line("Qualification:", data.qualification, y); y -= 22;
  line("Subjects:", data.subjects, y); y -= 22;
  line("Experience (years):", data.experience_years?.toString(), y); y -= 22;
  line("Expected Salary:", data.expected_salary, y); y -= 22;
  line("Availability:", data.availability, y); y -= 22;
  y -= 8;

  // Notes (multi-line)
  page.drawText("Notes:", { x: 55, y, size: 11, font: bold, color: text });
  const notes = (data.notes || "-").toString();
  const wrap = wrapText(notes, 80);
  let ny = y - 18;
  wrap.slice(0, 6).forEach((t) => {
    page.drawText(t, { x: 55, y: ny, size: 11, font, color: text });
    ny -= 16;
  });

  // Footer
  page.drawText("Generated by Admin Panel", {
    x: 40,
    y: 55,
    size: 9,
    font,
    color: rgb(0.35, 0.35, 0.35),
  });

  const pdfBytes = await pdfDoc.save();

  return new Response(pdfBytes, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `inline; filename="teacher_application_${data.id}.pdf"`,
    },
  });
}

function wrapText(str, maxLen) {
  const words = str.split(/\s+/);
  const lines = [];
  let line = "";
  for (const w of words) {
    if ((line + " " + w).trim().length > maxLen) {
      lines.push(line.trim());
      line = w;
    } else {
      line = (line + " " + w).trim();
    }
  }
  if (line.trim()) lines.push(line.trim());
  return lines;
}
